import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='container mx-auto px-2'>
        <h6 className='text-3xl font-bold text-red-300'>hello</h6>
      </main>
    </div>
  );
}
